import "./globals.css";
import Header from "@/components/layout/header";
import Navigation from "@/components/layout/navigation";
import { SessionProvider } from "@/components/providers/SessionProvider";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Velobuddy",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`${notoSansJp.className} antialiased`}>
				<SessionProvider>
					<div className="flex h-screen w-screen flex-col items-center justify-center text-zinc-700">
						<Header />
						{children}
						<Navigation />
					</div>
				</SessionProvider>
			</body>
		</html>
	);
}
